In [1]:
import numpy as np

### Array creation

In [8]:
test_array1 = np.array([1,4,5,8],int)
test_array2 = np.array([1,4,5,8],float) # int와 float 간 출력 형태의 차이가 있음
print(test_array1)
print(test_array2)
type(test_array[3])

[1 4 5 8]
[1. 4. 5. 8.]


numpy.float64

- numpy는 np.array 함수를 활용하여 배열을 생성함
- numpy는 하나의 데이터 type만 배열에 넣을 수 있음
- List와 가장 큰 차이점, Dynamic typing not supported (여러가지 데이터타입 불가)
- C의 Array를 사용하여 배열을 생성함

### Array shape

In [9]:
vector = [1, 2, 3, 4]
np.array(vector, int).shape

(4,)

In [10]:
matrix = [[1, 2, 5, 8],[1, 2, 5, 8],[1, 2, 5, 8]]
np.array(matrix, int).shape

(3, 4)

In [11]:
tensor = [[[1, 2, 5, 8],[1, 2, 5, 8],[1, 2, 5, 8]],
          [[1, 2, 5, 8],[1, 2, 5, 8],[1, 2, 5, 8]],
          [[1, 2, 5, 8],[1, 2, 5, 8],[1, 2, 5, 8]],
          [[1, 2, 5, 8],[1, 2, 5, 8],[1, 2, 5, 8]]]
np.array(tensor, int).shape

(4, 3, 4)

In [13]:
np.array(vector, int).ndim
np.array(matrix, int).ndim
np.array(tensor, int).ndim

3

In [ ]:
np.array(vector, int).size
np.array(matrix, int).size
np.array(tensor, int).size

### reshape : array의 shape 크기를 변경함(element의 갯수는 동일)

In [15]:
test_matrix = [[1,2,3,4],[1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [16]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [17]:
np.array(test_matrix).reshape(8,).shape

(8,)

### flatten : 다차원 array를 1차원 array로 변환

In [18]:
test_matrix = [[[1,2,3,4],[1,2,3,4]], [[1,2,3,4],[1,2,3,4]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])